name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Prepare java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@5.0
      with:
        lein: 2.9.1  
    - uses: actions/checkout@v3
    - name: Bump version
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: test
      run: lein test
    - uses: akhileshns/heroku-deploy@v3.12.12 
      env:
        VERSION: ${{ steps.tag_version.outputs.new_tag }}
      with: 
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "xpfarm-tictactoe-api"
        heroku_email: "martin.hablak@gmail.com"
        usedocker: true
        docker_build_args: |
          VERSION
